### PR TITLE
Update docker / portainer versions

### PR DESCRIPTION
**Pull request by irctrakz**
Update to current Docker (19.03.13) and Portainer (2.0) versions.

### CODE REVIEW

**Comment by JediNite** [comment]
@irctrakz

Thanks for the pull request. Docket 19.03.08 is the last version of docker that seems to compile successfully compiles on the WD arm based NAS. All versions post this one produce a corrupted dockerd file. Currently with the OS5 releases, docker will not run on the EX4100 model at least. I am not sure on the other arm based models. I think the results have been better for intel based models.

Cheers

JediNite

**Comment by irctrakz** [comment]
Ah! Fair enough. I just got it updated and running on the PR4100 and thought it would be worth updating. Feel free to close this.

**Comment by stefaang** [comment]
Improved docker support in OS5 is coming, so I'll take this one along once it's there, okay?

**Comment by stefaang** [comment]
In an attempt to honour contributions, I'll merge this first 🥇

**Comment by stefaang** [comment]
fml this is into `OS5` branch.. I'll juggle a bit.

**Comment by irctrakz** [comment]
Sorry, saw that you had a refactor branch for OS5 and didn't want to mess with master!

**Pull request merged**
